curl -O http://mushinone.sakura.ne.jp/sound/enma-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/taiwan-enma.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ezo-enma.mp3
curl -O http://mushinone.sakura.ne.jp/sound/futahoshi-koorogi.rm
curl -O http://mushinone.sakura.ne.jp/sound/umetate-koorogi.rm
curl -O http://mushinone.sakura.ne.jp/sound/tsuzuresase.mp3
curl -O http://mushinone.sakura.ne.jp/sound/natsuno-tsuzuresase.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kogata-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kuchinaga.mp3
curl -O http://mushinone.sakura.ne.jp/sound/mitsukado.mp3
curl -O http://mushinone.sakura.ne.jp/sound/oookame.mp3
curl -O http://mushinone.sakura.ne.jp/sound/haraokame.mp3
curl -O http://mushinone.sakura.ne.jp/sound/moriokame2.mp3
curl -O http://mushinone.sakura.ne.jp/sound/tanbookame_kugirinaki.mp3
curl -O http://mushinone.sakura.ne.jp/sound/tanbo-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kuma-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hime-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kamado.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kurotsuya.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kumasuzumushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kuchiki-koorogi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/madara_cricket1_high_rate_short.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kantan.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hirobane-kantan.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kogata-kantan.mp3
curl -O http://mushinone.sakura.ne.jp/sound/madara-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kawara-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hama-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/shiba-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/nettai-shibasuzu2.rm
curl -O http://mushinone.sakura.ne.jp/sound/yachi-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ezo-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hime-suzu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kinhibari.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kaya-hibari.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kusahibari.mp3
curl -O http://mushinone.sakura.ne.jp/sound/yamato-hibari.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kanetataki.mp3
curl -O http://mushinone.sakura.ne.jp/sound/iso-kanetataki.mp3
curl -O http://mushinone.sakura.ne.jp/sound/usuiro.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hoshi-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/onaga.mp3
curl -O http://mushinone.sakura.ne.jp/sound/sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kobane-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/futatsutoge.mp3
curl -O http://mushinone.sakura.ne.jp/sound/izu-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kasumi-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hisago.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kayakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hime-kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/oo-kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/sibukiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kubikiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/T.orientalis.mp3
curl -O http://mushinone.sakura.ne.jp/sound/T.yama.mp3
curl -O http://mushinone.sakura.ne.jp/sound/karafuto-kirigirisu.rm
curl -O http://mushinone.sakura.ne.jp/sound/kirigirisu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/nishi-kirigirisu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hanenaga-kirigirisu.rm
curl -O http://mushinone.sakura.ne.jp/sound/himegisu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kobane-himegisu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hayashino.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hatakeno.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kutsuwamushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/taiwan-kutsuwamushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/tsuyumushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ashiguro-tsuyumushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/sesuji-tsuyumushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ezo-tsuyumushi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hosokubi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/yama-kudamakimodoki.rm
curl -O http://mushinone.sakura.ne.jp/sound/sato-kudamakimodoki.rm
curl -O http://mushinone.sakura.ne.jp/sound/hime-kudamaki_male_and_female.mp3
curl -O http://mushinone.sakura.ne.jp/sound/heriguro.mp3
curl -O http://mushinone.sakura.ne.jp/sound/usuiro.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hoshi-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/onaga.mp3
curl -O http://mushinone.sakura.ne.jp/sound/sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kobane-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/futatsutoge.mp3
curl -O http://mushinone.sakura.ne.jp/sound/izu-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kasumi-sasakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hisago.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kayakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hime-kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/oo-kusakiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/sibukiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kubikiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/kera.mp3
curl -O http://mushinone.sakura.ne.jp/sound/madara-batta.rm
curl -O http://mushinone.sakura.ne.jp/sound/tsumaguro-inagomodoki.rm
curl -O http://mushinone.sakura.ne.jp/sound/tonosama-batta.rm
curl -O http://mushinone.sakura.ne.jp/sound/kurumabattamodoki.rm
curl -O http://mushinone.sakura.ne.jp/sound/kawara-batta.rm
curl -O http://mushinone.sakura.ne.jp/sound/naki-inago.mp3
curl -O http://mushinone.sakura.ne.jp/sound/hirobane-hinabatta.rm
curl -O http://mushinone.sakura.ne.jp/sound/hina-batta.mp3
curl -O http://mushinone.sakura.ne.jp/sound/chishima-hinabatta.rm
curl -O http://mushinone.sakura.ne.jp/sound/haruzemi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ezo-haruzemi.mp3
curl -O http://mushinone.sakura.ne.jp/sound/ootobi-sashigame.mp3
curl -O http://mushinone.sakura.ne.jp/sound/akashima-sashigame.rm
curl -O http://mushinone.sakura.ne.jp/sound/ashimadaraaka-sashigame.rm
curl -O http://mushinone.sakura.ne.jp/sound/kiiro-sashigame.mp3
curl -O http://mushinone.sakura.ne.jp/sound/gomadara-kamikiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/nokogiri-kamikiri.mp3
curl -O http://mushinone.sakura.ne.jp/sound/togehige-torakamikiri.rm
curl -O http://mushinone.sakura.ne.jp/sound/yotsuboshi-keshikisui.rm
curl -O http://mushinone.sakura.ne.jp/sound/miyamaobi-ookinoko.rm
curl -O http://mushinone.sakura.ne.jp/sound/ubatama-kometsuki.mp3
curl -O http://mushinone.sakura.ne.jp/sound/miidera-gomimushi.rm
curl -O http://mushinone.sakura.ne.jp/sound/ashibuto-hanaabu.mp3
curl -O http://mushinone.sakura.ne.jp/sound/biroudo-tsuriabu.mp3
